name: Upload 

# Controls when the workflow will run
on:
  # Trigger workflow when a release is made

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Create ZIP archive
        run: zip -r tekaxic.zip $GITHUB_WORKSPACE -x "$GITHUB_WORKSPACE/.git/*" 

      - name: Upload
        run: curl --upload-file tekaxic.zip https://transfer.sh

